version: "3"

services:
  # postgres:
  #   image: "postgres:14"
  #   volumes:
  #     - ./init-scripts/postgres:/docker-entrypoint-initdb.d/
  #   environment:
  #     - "POSTGRES_USER=nestjs_query"
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"
  #   expose:
  #     - "5432"
  #   ports:
  #     - "5436:5432"
  # mysql:
  #   platform: linux/x86_64
  #   image: "mysql:8"
  #   volumes:
  #     - ./init-scripts/mysql:/docker-entrypoint-initdb.d/
  #   environment:
  #     - "MYSQL_USER=nestjs_query"
  #     - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"

  localCircle:
  image: ed12699/local-circle:latest
  ports:
    - "4456:4456"
  depends_on:
    - redis
    - mongo
  environment:
    SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    REGION: ${REGION}
    BUCKET: ${BUCKET}
    DB_USER: "DB_USER"
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    REDIS_DB: ${REDIS_DB}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_PRIFIX: ${REDIS_PRIFIX}
  volumes:
    - ~/app/local-circle/logs:/app/logs

  redis:
    image: "redis:6"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
  mongo:
    image: "mongo:6.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local-circle
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init/-scripts/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # mongo-express:
    #   image: "mongo-express:latest"
    #   restart: always
    #   ports:
    #     - 8081:8081
